### ISSUE TITLE
Fails on Windows

### ISSUE THREAD

**Issue by MinchinWeb** [papermerge/mglib#1]
This [line](https://github.com/papermerge/mglib/blob/14370d35b2ae25219e91e8e0b8e9666f102b53a4/mglib/pdfinfo.py#L82) of `pdfinfo,py` has a hard-coded path, and thus fails on Windows. The lines of interest:

```py
    cmd = ["/usr/bin/pdfinfo", filepath]
    compl = subprocess.run(
        cmd,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE
    )
```

I think this is keeping *papermerge* from being able to upload a file without error on Windows.

c.f. <https://github.com/ciur/papermerge/issues/43> and <https://github.com/ciur/papermerge-worker/issues/2>

**Comment by ciur** [comment]
First of all Papermerge DMS is not designed to run on Windows :)
But I agree with you that mentioned line is not portable :-1: 

Any idea how to write that code portable ?

**Comment by MinchinWeb** [comment]
There's several options that come to mind:

1. Use a Python library rather than a system executable. Then your program can run anywhere Python runs. This has the advantage of simplifying the installation too, because all your requirements can be listed in your `requirements.txt` file, or in `setup.py`. (It seems every flavour of linux has a slightly different package manager, and sometimes packages have different names...) To get the page count of a PDF, there seems to be several options out there. This would be my preferred option.
2. Use a Python wrapper to a system exactable. Then someone else has worked out the cross platform issues.
3. Assume/require that the exactable be on the system PATH. Then you can just use the exactable name (`pdfinfo`). This should work cross platform.
4. Use system testing code to determine the path:
    ```python
    if sys.platform == "Windows":
        cmd = ["pdfinfo", filepath]
    else:
        cmd = ["/usr/bin/pdfinfo", filepath]
    ```
    (Here, this assumes that the exactable is on the system PATH for Windows. You could put in the default install path too, but I don't know that at the moment.)
5. Have the executable path set (or override-able) via your program settings.
6. Have the executable path set (or override-able) via environmental variables settings.

As for supporting Windows, Python runs well on Windows, and I don't see anything within the design goals of Papermerge that would keep it from being functional on Windows, so I hope you can find something that works.

If you want, I can put together a pull request for #1 (use a Python library), just let me know.

**Comment by ciur** [comment]
This issue was [fixed as part of this ticket in papermerge project.](https://github.com/ciur/papermerge/issues/63).
Binary paths are not hardcoded anymore. 
[Documentation was updated as well.](https://papermerge.readthedocs.io/en/latest/settings.html#binary-dependencies)
In short, all paths can be changed using BINARY_xyz settings. Example:

> BINARY_PDFINFO = "c:\\windows\\bin""
